### ISSUE TITLE
Typo in name of impact category in ReCiPe

### ISSUE THREAD

**Issue by tur-ium** [USEPA/LCIAformatter#124]
Hi Ben, 

In ReCiPe Midpoint H there is a small typo in the impact category name. It should be "Ecosystem damage ozone formation", the first "m" is missing in the version downloaded from the Commons. I think the correction is needed on line 11 in /lciafmt/data/ReCiPe2016_endpoint_to_midpoint.csv#L10

All the best,
Artur

**Comment by bl-young** [comment]
thanks! It's actually an issue in the underlying workbooks, but we will correct the typo in the next release.
