### ISSUE TITLE
typo in installation instructions

### ISSUE THREAD

**Issue by mfastudillo** [USEPA/LCIAformatter#2]
Hi, there are some missing `"r"` in the installation [instructions](https://github.com/USEPA/LCIAformatter/wiki/Install) ;)

`pip install git+https://github.com/USEPA/LCIAfomatter.git@v0.1-alpha#egg=LCIAfomatter`

should be 

`pip install git+https://github.com/USEPA/LCIAformatter.git@v0.1-alpha#egg=LCIAformatter`

**Comment by WesIngwersen** [comment]
Thank you Miguel, that's corrected!
