### ISSUE TITLE
Duplicate impact factors for flows

### ISSUE THREAD

**Issue by jump2conclusionsmatt** [USEPA/LCIAformatter#31]
lciaformatter creates duplicate emission factors for several emissions. I know at the very least this applies to /emission/air/carbon dioxide and the global warming category. There are 4 factors of 1.0 for it in the json-ld. These duplicate factors also get imported into openLCA. I don't know if it can somehow affect impact analysis calculations.

I use this script to generate json-lds for the fedelemflows and lciaformatter:
```
import fedelemflowlist
import lciafmt
import datetime


fedflows=fedelemflowlist.get_flows()
traci21=lciafmt.get_method('TRACI 2.1')
traci21_mapped=lciafmt.map_flows(traci21)

current_time=datetime.datetime.now()
current_date_string=current_time.strftime('%m%d%Y')
fedelemflowlist.write_jsonld(fedflows,f"./fedflows_{current_date_string}.zip")
lciafmt.to_jsonld(traci21_mapped,f"./traci21_{current_date_string}.zip")
```

**Comment by WesIngwersen** [comment]
thanks for reporting @jump2conclusionsmatt , assigning it to@hottleta . troy please evaluate and work on or reassign

**Comment by WesIngwersen** [comment]
We've had a duplication issue #6 in the past. Not sure if this related.

**Comment by bl-young** [comment]
@jump2conclusionsmatt  can you confirm what version of lciaformatter you are using?

**Comment by jump2conclusionsmatt** [comment]
I'm up to date with whatever's in Master.

**Comment by bl-young** [comment]
When applying the mapping you need to specify the system

See [Apply flow mappings](https://github.com/USEPA/LCIAformatter/wiki/Using-lciafmt#apply-flow-mappings), notably the second box of code where system="TRACI2.1"

As an example, note the TRACI script [here](https://github.com/USEPA/LCIAformatter/blob/master/examples/traci.py#L28)

Otherwise it will pull and apply all mappings resulting in potential duplicates.

**Comment by jump2conclusionsmatt** [comment]
Ah. RTFM, got it. I had just assumed that when the call went out to the fedelemflowlist that it would just be pulling the the fedelemflows.

Still may be worth putting in a `drop_duplicates(subset=["Indicator","Flow UUID","Characterization Factor"],keep="first")` or something somewhere, unless there's a reason that someone would want all the mappings returned with duplicate factors.
