### ISSUE TITLE
assign version on json-ld export

### ISSUE THREAD

**Issue by bl-young** [USEPA/LCIAformatter#52]
When creating a json-ld version of a method, the version number should reflect the version of lciafmt

**Comment by bl-young** [comment]
Most likely somewhere [here](https://github.com/USEPA/LCIAformatter/blob/master/lciafmt/jsonld.py#L82)

**Comment by WesIngwersen** [comment]
Yes, I imagine in the description, which uses the method metadata, defined [here](https://github.com/USEPA/LCIAformatter/blob/edbe996a19f37fb3931ae00c4bbd2f6ca15b2e6b/lciafmt/util.py#L179)
So the lciafmt version could be added there to be attached to all methods

**Comment by bl-young** [comment]
![image](https://user-images.githubusercontent.com/44471635/117167404-383a2880-ad95-11eb-9623-f2ff64a36406.png)

This image is probably old, but I'm referring to the actual version field within openLCA. It will be helpful when importing and "updating" methods upon JSON-ld import

**Comment by WesIngwersen** [comment]
Yes the version field is an option, but there is a potential source of confusion to the user with the LCIAformatter version and the method version itself. Ideally we can touch on this with the Federal LCA data working group when we meet.
