### ISSUE TITLE
xlsx files no longer supported by xlrd

### ISSUE THREAD

**Issue by bl-young** [USEPA/LCIAformatter#55]
Starting in v2.0.0 of xlrd, xlsx files are longer supported.

A user who has the latest version will get errors from [TRACI](https://github.com/USEPA/LCIAformatter/blob/master/lciafmt/traci.py#L70) and [ReCiPe](https://github.com/USEPA/LCIAformatter/blob/master/lciafmt/recipe.py#L120) and perhaps in other spots.

[Recommendation](https://stackoverflow.com/a/65266497) is to use openpyxl or simply rely on the read_excel in pandas > 1.2 which defaults to openpyxl.

A short term fix could require xlrd 1.2.0

**Comment by bl-young** [comment]
see https://github.com/USEPA/LCIAformatter/commit/6410043d25b87cf6256743c25d90a5b27dafa397

**Comment by WesIngwersen** [comment]
closing this since this issue is part of issue #57
