### ISSUE TITLE
xlrd error getting methods

### ISSUE THREAD

**Issue by mfastudillo** [USEPA/LCIAformatter#57]
Hi!

I was trying the library and running `recipe2016 = lciafmt.get_method(lciafmt.Method.RECIPE_2016)` I got the following error

![imagen](https://user-images.githubusercontent.com/11621547/123506999-6cc8b300-d667-11eb-94e3-c283d6ae8ad2.png)

it seems to be caused by xlrd [ending support](https://groups.google.com/g/python-excel/c/IRa8IWq_4zk/m/Af8-hrRnAgAJ) for non-xls files. I installed pandas before lciafmt, and I ended up with version 2.0.1 fo xlrd... an alternative may be to switch to openpyx for xlsx files...

openjournals/joss-reviews#3392

**Comment by bl-young** [comment]
@mfastudillo yes it appears that the latest release of xlrd will not work. I will likely switch to openpyxl. In the meantime, you may want to downgrade to 1.2 to continue testing

**Comment by bl-young** [comment]
requirements specified <2.0 for temporary resolution https://github.com/USEPA/LCIAformatter/commit/6410043d25b87cf6256743c25d90a5b27dafa397

**Comment by mfastudillo** [comment]
Hi

I ended up cloning the repo and using the setup file of the joss_review branch to install the library. When I try to get the TRACI method I have a different error.

![image](https://user-images.githubusercontent.com/11621547/124354711-9bb5ca80-dc0d-11eb-8937-468b24dea4c9.png)

the xlrd version installed is 1.2.0

**Comment by WesIngwersen** [comment]
It appears that we should try the alternative library proposed _openpyxl_ because of these versioning issues with _xlrd_ 
@bl-young

**Comment by bl-young** [comment]
I will work on resolving this issue to shift to openpyxl and will let you know when it has been fixed @mfastudillo @tngTUDOR. It seems that starting with python 3.9 xlrd will not work even with version 1.2
