### ISSUE TITLE
Install instructions in README.md

### ISSUE THREAD

**Issue by tngTUDOR** [USEPA/LCIAformatter#58]
I often see install instructions in the README of a repository.

- [x] I suggest you add the install instructions from the wiki to the README.
- [x] Also it could be interesting to add as option an install flow that would look like:
```
git clone https://github.com/USEPA/LCIAformatter.git
cd LCIAformatter
pip install . # or pip install -e . for devs
```

**Comment by bl-young** [comment]
Updated readme here https://github.com/USEPA/LCIAformatter/commit/d496c0e0f84636e089076acb42a684b60460d3ca

**Comment by tngTUDOR** [comment]
openjournals/joss-reviews#3392
