### ISSUE TITLE
Duplicates in TRACI mappings

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/LCIAformatter#6]
With updates to TRACI mapping we now have more coverage of mappings with just primary contexts, like TRACI 'air', 'soil', and 'water', but there are duplicate mappings in the list, see the attached subset for 1,4-DIOXANE. This needs to now be addressed.
[14Dioxanemappings_13Jan2020.xlsx](https://github.com/USEPA/Federal-LCA-Commons-Elementary-Flow-List/files/4056463/14Dioxanemappings_13Jan2020.xlsx)

**Comment by WesIngwersen** [comment]
Sounds good @bl-young please address. thanks.

**Comment by WesIngwersen** [comment]
According to @bl-young some duplicates still exist. In the new function I created to add average factors, I don't check if an average already exists. 
After creating the average factors [here](https://github.com/USEPA/LCIAformatter/blob/master/lciafmt/util.py#L84)
you could take that result and make sure that no other factors already exist in df for that flowable, context, and impact category, and if they do, remove then from df_secondary_agg before concatenating.

**Comment by bl-young** [comment]
The result of this function is good. The df that is returned contains no duplicates. I think its within fmap but am still searching

**Comment by bl-young** [comment]
"unspecified" was being ignored in the flow mapper causing the new contexts like "air/unspecified" to be mapped based on "air" when performing the mapping. I don't know if there are other ramifications to removing it within fmap in other use cases #5 
Doing so seems to resolve the duplicates issue with TRACI

If the "unspecified" phrase is key in other contexts we can adjust the phrase we use for developing the average CFs in both LCIAformatter and FEDEFL TRACI context mapping

**Comment by WesIngwersen** [comment]
Resolved with latest pull request #5
