### ISSUE TITLE
"fatal: not a git repository" error on import of lciafmt 

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/LCIAformatter#60]
reported first by @mfastudillo. Also replicated it. Appears when working in python outside of the folder i..e working from pip installed version

**Comment by WesIngwersen** [comment]
Believed to occur in this line
https://github.com/USEPA/LCIAformatter/blob/9c225425f6f62a47cfd7cf9f6f05f987db6d6ed8/lciafmt/util.py#L41

**Comment by bl-young** [comment]
yes we discovered this can happen in other packages like flowsa too. Despite the error message, the try/except works as intended (`git_hash` is None). It is not actually a fatal error. But certainly the error message itself is not ideal. Perhaps there is a way to silence it within subprocess

**Comment by WesIngwersen** [comment]
Yes either that (supress the error message) or run a separate subprocess command just to check if a git repo is present first before proceeding. I think I prefer the latter.
