### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by MaximeAgez** [USEPA/LCIAformatter#80]
Hi!
When I try to install the module following the pip install command I get an error (see below).

I'm using Anaconda, the os is Windows and I tried installing on a freshly new environment.

![image](https://user-images.githubusercontent.com/24285636/149167016-60d9c340-9ca4-494f-91dd-257699e05eb8.png)

Thanks.

**Comment by a-w-beck** [comment]
Hi @MaximeAgez, do you have a conda env.yaml file you could share? 

Numpy 1.20.1 requires Python >= 3.7, which may be constraining pip's search for an adequate Numpy version.

**Comment by MaximeAgez** [comment]
I upgraded my python version and everything works now. Thanks for the help :)
